package com.example.demo.reading.mapper;

import com.example.demo.reading.model.po.HeadmasterMessagePo;
import com.example.demo.reading.model.po.HeadmasterMessagePoExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;
@Mapper
public interface HeadmasterMessagePoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table headmaster_message
     *
     * @mbggenerated Wed Sep 25 14:08:47 CST 2019
     */
    int countByExample(HeadmasterMessagePoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table headmaster_message
     *
     * @mbggenerated Wed Sep 25 14:08:47 CST 2019
     */
    int deleteByExample(HeadmasterMessagePoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table headmaster_message
     *
     * @mbggenerated Wed Sep 25 14:08:47 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table headmaster_message
     *
     * @mbggenerated Wed Sep 25 14:08:47 CST 2019
     */
    int insert(HeadmasterMessagePo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table headmaster_message
     *
     * @mbggenerated Wed Sep 25 14:08:47 CST 2019
     */
    int insertSelective(HeadmasterMessagePo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table headmaster_message
     *
     * @mbggenerated Wed Sep 25 14:08:47 CST 2019
     */
    List<HeadmasterMessagePo> selectByExampleWithBLOBs(HeadmasterMessagePoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table headmaster_message
     *
     * @mbggenerated Wed Sep 25 14:08:47 CST 2019
     */
    List<HeadmasterMessagePo> selectByExample();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table headmaster_message
     *
     * @mbggenerated Wed Sep 25 14:08:47 CST 2019
     */
    HeadmasterMessagePo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table headmaster_message
     *
     * @mbggenerated Wed Sep 25 14:08:47 CST 2019
     */
    int updateByExampleSelective(@Param("record") HeadmasterMessagePo record, @Param("example") HeadmasterMessagePoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table headmaster_message
     *
     * @mbggenerated Wed Sep 25 14:08:47 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") HeadmasterMessagePo record, @Param("example") HeadmasterMessagePoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table headmaster_message
     *
     * @mbggenerated Wed Sep 25 14:08:47 CST 2019
     */
    int updateByExample(@Param("record") HeadmasterMessagePo record, @Param("example") HeadmasterMessagePoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table headmaster_message
     *
     * @mbggenerated Wed Sep 25 14:08:47 CST 2019
     */
    int updateByPrimaryKeySelective(HeadmasterMessagePo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table headmaster_message
     *
     * @mbggenerated Wed Sep 25 14:08:47 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(HeadmasterMessagePo record);
}