package com.example.demo.essay.mapper;

import com.example.demo.essay.model.po.EssayInfoPo;
import com.example.demo.essay.model.po.EssayInfoPoExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface EssayInfoPoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table essay_info
     *
     * @mbggenerated Mon Jul 15 19:56:38 CST 2019
     */
    int countByExample(EssayInfoPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table essay_info
     *
     * @mbggenerated Mon Jul 15 19:56:38 CST 2019
     */
    int deleteByExample(EssayInfoPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table essay_info
     *
     * @mbggenerated Mon Jul 15 19:56:38 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table essay_info
     *
     * @mbggenerated Mon Jul 15 19:56:38 CST 2019
     */
    int insert(EssayInfoPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table essay_info
     *
     * @mbggenerated Mon Jul 15 19:56:38 CST 2019
     */
    int insertSelective(EssayInfoPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table essay_info
     *
     * @mbggenerated Mon Jul 15 19:56:38 CST 2019
     */
    List<EssayInfoPo> selectByExample(EssayInfoPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table essay_info
     *
     * @mbggenerated Mon Jul 15 19:56:38 CST 2019
     */
    EssayInfoPo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table essay_info
     *
     * @mbggenerated Mon Jul 15 19:56:38 CST 2019
     */
    int updateByExampleSelective(@Param("record") EssayInfoPo record, @Param("example") EssayInfoPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table essay_info
     *
     * @mbggenerated Mon Jul 15 19:56:38 CST 2019
     */
    int updateByExample(@Param("record") EssayInfoPo record, @Param("example") EssayInfoPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table essay_info
     *
     * @mbggenerated Mon Jul 15 19:56:38 CST 2019
     */
    int updateByPrimaryKeySelective(EssayInfoPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table essay_info
     *
     * @mbggenerated Mon Jul 15 19:56:38 CST 2019
     */
    int updateByPrimaryKey(EssayInfoPo record);
}