package com.example.demo.essay.mapper;

import com.example.demo.essay.model.po.EssaySignInPo;
import com.example.demo.essay.model.po.EssaySignInPoExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface EssaySignInPoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table essay_sign_in
     *
     * @mbggenerated Mon Apr 08 10:18:34 CST 2019
     */
    int countByExample(EssaySignInPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table essay_sign_in
     *
     * @mbggenerated Mon Apr 08 10:18:34 CST 2019
     */
    int deleteByExample(EssaySignInPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table essay_sign_in
     *
     * @mbggenerated Mon Apr 08 10:18:34 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table essay_sign_in
     *
     * @mbggenerated Mon Apr 08 10:18:34 CST 2019
     */
    int insert(EssaySignInPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table essay_sign_in
     *
     * @mbggenerated Mon Apr 08 10:18:34 CST 2019
     */
    int insertSelective(EssaySignInPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table essay_sign_in
     *
     * @mbggenerated Mon Apr 08 10:18:34 CST 2019
     */
    List<EssaySignInPo> selectByExample(EssaySignInPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table essay_sign_in
     *
     * @mbggenerated Mon Apr 08 10:18:34 CST 2019
     */
    EssaySignInPo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table essay_sign_in
     *
     * @mbggenerated Mon Apr 08 10:18:34 CST 2019
     */
    int updateByExampleSelective(@Param("record") EssaySignInPo record, @Param("example") EssaySignInPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table essay_sign_in
     *
     * @mbggenerated Mon Apr 08 10:18:34 CST 2019
     */
    int updateByExample(@Param("record") EssaySignInPo record, @Param("example") EssaySignInPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table essay_sign_in
     *
     * @mbggenerated Mon Apr 08 10:18:34 CST 2019
     */
    int updateByPrimaryKeySelective(EssaySignInPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table essay_sign_in
     *
     * @mbggenerated Mon Apr 08 10:18:34 CST 2019
     */
    int updateByPrimaryKey(EssaySignInPo record);
}