package com.example.demo.essay.mapper;

import com.example.demo.essay.model.po.EssayAwardPo;
import com.example.demo.essay.model.po.EssayAwardPoExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface EssayAwardPoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table essay_award
     *
     * @mbggenerated Wed Apr 03 15:18:36 CST 2019
     */
    int countByExample(EssayAwardPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table essay_award
     *
     * @mbggenerated Wed Apr 03 15:18:36 CST 2019
     */
    int deleteByExample(EssayAwardPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table essay_award
     *
     * @mbggenerated Wed Apr 03 15:18:36 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table essay_award
     *
     * @mbggenerated Wed Apr 03 15:18:36 CST 2019
     */
    int insert(EssayAwardPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table essay_award
     *
     * @mbggenerated Wed Apr 03 15:18:36 CST 2019
     */
    int insertSelective(EssayAwardPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table essay_award
     *
     * @mbggenerated Wed Apr 03 15:18:36 CST 2019
     */
    List<EssayAwardPo> selectByExample(EssayAwardPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table essay_award
     *
     * @mbggenerated Wed Apr 03 15:18:36 CST 2019
     */
    EssayAwardPo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table essay_award
     *
     * @mbggenerated Wed Apr 03 15:18:36 CST 2019
     */
    int updateByExampleSelective(@Param("record") EssayAwardPo record, @Param("example") EssayAwardPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table essay_award
     *
     * @mbggenerated Wed Apr 03 15:18:36 CST 2019
     */
    int updateByExample(@Param("record") EssayAwardPo record, @Param("example") EssayAwardPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table essay_award
     *
     * @mbggenerated Wed Apr 03 15:18:36 CST 2019
     */
    int updateByPrimaryKeySelective(EssayAwardPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table essay_award
     *
     * @mbggenerated Wed Apr 03 15:18:36 CST 2019
     */
    int updateByPrimaryKey(EssayAwardPo record);
}