package com.example.demo.reading.model.po;

public class HeadmasterMessagePo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column headmaster_message.id
     *
     * @mbggenerated Wed Sep 25 14:08:47 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column headmaster_message.headmaster_message
     *
     * @mbggenerated Wed Sep 25 14:08:47 CST 2019
     */
    private String headmasterMessage;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column headmaster_message.id
     *
     * @return the value of headmaster_message.id
     *
     * @mbggenerated Wed Sep 25 14:08:47 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column headmaster_message.id
     *
     * @param id the value for headmaster_message.id
     *
     * @mbggenerated Wed Sep 25 14:08:47 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column headmaster_message.headmaster_message
     *
     * @return the value of headmaster_message.headmaster_message
     *
     * @mbggenerated Wed Sep 25 14:08:47 CST 2019
     */
    public String getHeadmasterMessage() {
        return headmasterMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column headmaster_message.headmaster_message
     *
     * @param headmasterMessage the value for headmaster_message.headmaster_message
     *
     * @mbggenerated Wed Sep 25 14:08:47 CST 2019
     */
    public void setHeadmasterMessage(String headmasterMessage) {
        this.headmasterMessage = headmasterMessage == null ? null : headmasterMessage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table headmaster_message
     *
     * @mbggenerated Wed Sep 25 14:08:47 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", headmasterMessage=").append(headmasterMessage);
        sb.append("]");
        return sb.toString();
    }
}