package com.example.demo.essay.model.po;

import java.sql.Timestamp;

public class ClickCountPo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column click_count.id
     *
     * @mbggenerated Tue Apr 09 14:01:52 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column click_count.essay_id
     *
     * @mbggenerated Tue Apr 09 14:01:52 CST 2019
     */
    private String essayId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column click_count.click_count
     *
     * @mbggenerated Tue Apr 09 14:01:52 CST 2019
     */
    private Integer clickCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column click_count.gmt_create
     *
     * @mbggenerated Tue Apr 09 14:01:52 CST 2019
     */
    private Timestamp gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column click_count.gmt_modified
     *
     * @mbggenerated Tue Apr 09 14:01:52 CST 2019
     */
    private Timestamp gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column click_count.id
     *
     * @return the value of click_count.id
     *
     * @mbggenerated Tue Apr 09 14:01:52 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column click_count.id
     *
     * @param id the value for click_count.id
     *
     * @mbggenerated Tue Apr 09 14:01:52 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column click_count.essay_id
     *
     * @return the value of click_count.essay_id
     *
     * @mbggenerated Tue Apr 09 14:01:52 CST 2019
     */
    public String getEssayId() {
        return essayId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column click_count.essay_id
     *
     * @param essayId the value for click_count.essay_id
     *
     * @mbggenerated Tue Apr 09 14:01:52 CST 2019
     */
    public void setEssayId(String essayId) {
        this.essayId = essayId == null ? null : essayId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column click_count.click_count
     *
     * @return the value of click_count.click_count
     *
     * @mbggenerated Tue Apr 09 14:01:52 CST 2019
     */
    public Integer getClickCount() {
        return clickCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column click_count.click_count
     *
     * @param clickCount the value for click_count.click_count
     *
     * @mbggenerated Tue Apr 09 14:01:52 CST 2019
     */
    public void setClickCount(Integer clickCount) {
        this.clickCount = clickCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column click_count.gmt_create
     *
     * @return the value of click_count.gmt_create
     *
     * @mbggenerated Tue Apr 09 14:01:52 CST 2019
     */
    public Timestamp getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column click_count.gmt_create
     *
     * @param gmtCreate the value for click_count.gmt_create
     *
     * @mbggenerated Tue Apr 09 14:01:52 CST 2019
     */
    public void setGmtCreate(Timestamp gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column click_count.gmt_modified
     *
     * @return the value of click_count.gmt_modified
     *
     * @mbggenerated Tue Apr 09 14:01:52 CST 2019
     */
    public Timestamp getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column click_count.gmt_modified
     *
     * @param gmtModified the value for click_count.gmt_modified
     *
     * @mbggenerated Tue Apr 09 14:01:52 CST 2019
     */
    public void setGmtModified(Timestamp gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table click_count
     *
     * @mbggenerated Tue Apr 09 14:01:52 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", essayId=").append(essayId);
        sb.append(", clickCount=").append(clickCount);
        sb.append(", gmtCreate=").append(gmtCreate);
        sb.append(", gmtModified=").append(gmtModified);
        sb.append("]");
        return sb.toString();
    }
}