package com.example.demo.essay.model.po;

import java.sql.Timestamp;

public class EssaySignInPo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column essay_sign_in.id
     *
     * @mbggenerated Mon Apr 08 10:18:34 CST 2019
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column essay_sign_in.essay_id
     *
     * @mbggenerated Mon Apr 08 10:18:34 CST 2019
     */
    private String essayId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column essay_sign_in.essay_name
     *
     * @mbggenerated Mon Apr 08 10:18:34 CST 2019
     */
    private String essayName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column essay_sign_in.name
     *
     * @mbggenerated Mon Apr 08 10:18:34 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column essay_sign_in.puid
     *
     * @mbggenerated Mon Apr 08 10:18:34 CST 2019
     */
    private Integer puid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column essay_sign_in.sex
     *
     * @mbggenerated Mon Apr 08 10:18:34 CST 2019
     */
    private Integer sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column essay_sign_in.unit
     *
     * @mbggenerated Mon Apr 08 10:18:34 CST 2019
     */
    private String unit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column essay_sign_in.identity
     *
     * @mbggenerated Mon Apr 08 10:18:34 CST 2019
     */
    private String identity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column essay_sign_in.phone
     *
     * @mbggenerated Mon Apr 08 10:18:34 CST 2019
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column essay_sign_in.mail
     *
     * @mbggenerated Mon Apr 08 10:18:34 CST 2019
     */
    private String mail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column essay_sign_in.note
     *
     * @mbggenerated Mon Apr 08 10:18:34 CST 2019
     */
    private String note;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column essay_sign_in.status
     *
     * @mbggenerated Mon Apr 08 10:18:34 CST 2019
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column essay_sign_in.is_display
     *
     * @mbggenerated Mon Apr 08 10:18:34 CST 2019
     */
    private Integer isDisplay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column essay_sign_in.gmt_create
     *
     * @mbggenerated Mon Apr 08 10:18:34 CST 2019
     */
    private Timestamp gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column essay_sign_in.gmt_modified
     *
     * @mbggenerated Mon Apr 08 10:18:34 CST 2019
     */
    private Timestamp gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column essay_sign_in.id
     *
     * @return the value of essay_sign_in.id
     *
     * @mbggenerated Mon Apr 08 10:18:34 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column essay_sign_in.id
     *
     * @param id the value for essay_sign_in.id
     *
     * @mbggenerated Mon Apr 08 10:18:34 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column essay_sign_in.essay_id
     *
     * @return the value of essay_sign_in.essay_id
     *
     * @mbggenerated Mon Apr 08 10:18:34 CST 2019
     */
    public String getEssayId() {
        return essayId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column essay_sign_in.essay_id
     *
     * @param essayId the value for essay_sign_in.essay_id
     *
     * @mbggenerated Mon Apr 08 10:18:34 CST 2019
     */
    public void setEssayId(String essayId) {
        this.essayId = essayId == null ? null : essayId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column essay_sign_in.essay_name
     *
     * @return the value of essay_sign_in.essay_name
     *
     * @mbggenerated Mon Apr 08 10:18:34 CST 2019
     */
    public String getEssayName() {
        return essayName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column essay_sign_in.essay_name
     *
     * @param essayName the value for essay_sign_in.essay_name
     *
     * @mbggenerated Mon Apr 08 10:18:34 CST 2019
     */
    public void setEssayName(String essayName) {
        this.essayName = essayName == null ? null : essayName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column essay_sign_in.name
     *
     * @return the value of essay_sign_in.name
     *
     * @mbggenerated Mon Apr 08 10:18:34 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column essay_sign_in.name
     *
     * @param name the value for essay_sign_in.name
     *
     * @mbggenerated Mon Apr 08 10:18:34 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column essay_sign_in.puid
     *
     * @return the value of essay_sign_in.puid
     *
     * @mbggenerated Mon Apr 08 10:18:34 CST 2019
     */
    public Integer getPuid() {
        return puid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column essay_sign_in.puid
     *
     * @param puid the value for essay_sign_in.puid
     *
     * @mbggenerated Mon Apr 08 10:18:34 CST 2019
     */
    public void setPuid(Integer puid) {
        this.puid = puid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column essay_sign_in.sex
     *
     * @return the value of essay_sign_in.sex
     *
     * @mbggenerated Mon Apr 08 10:18:34 CST 2019
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column essay_sign_in.sex
     *
     * @param sex the value for essay_sign_in.sex
     *
     * @mbggenerated Mon Apr 08 10:18:34 CST 2019
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column essay_sign_in.unit
     *
     * @return the value of essay_sign_in.unit
     *
     * @mbggenerated Mon Apr 08 10:18:34 CST 2019
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column essay_sign_in.unit
     *
     * @param unit the value for essay_sign_in.unit
     *
     * @mbggenerated Mon Apr 08 10:18:34 CST 2019
     */
    public void setUnit(String unit) {
        this.unit = unit == null ? null : unit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column essay_sign_in.identity
     *
     * @return the value of essay_sign_in.identity
     *
     * @mbggenerated Mon Apr 08 10:18:34 CST 2019
     */
    public String getIdentity() {
        return identity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column essay_sign_in.identity
     *
     * @param identity the value for essay_sign_in.identity
     *
     * @mbggenerated Mon Apr 08 10:18:34 CST 2019
     */
    public void setIdentity(String identity) {
        this.identity = identity == null ? null : identity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column essay_sign_in.phone
     *
     * @return the value of essay_sign_in.phone
     *
     * @mbggenerated Mon Apr 08 10:18:34 CST 2019
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column essay_sign_in.phone
     *
     * @param phone the value for essay_sign_in.phone
     *
     * @mbggenerated Mon Apr 08 10:18:34 CST 2019
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column essay_sign_in.mail
     *
     * @return the value of essay_sign_in.mail
     *
     * @mbggenerated Mon Apr 08 10:18:34 CST 2019
     */
    public String getMail() {
        return mail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column essay_sign_in.mail
     *
     * @param mail the value for essay_sign_in.mail
     *
     * @mbggenerated Mon Apr 08 10:18:34 CST 2019
     */
    public void setMail(String mail) {
        this.mail = mail == null ? null : mail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column essay_sign_in.note
     *
     * @return the value of essay_sign_in.note
     *
     * @mbggenerated Mon Apr 08 10:18:34 CST 2019
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column essay_sign_in.note
     *
     * @param note the value for essay_sign_in.note
     *
     * @mbggenerated Mon Apr 08 10:18:34 CST 2019
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column essay_sign_in.status
     *
     * @return the value of essay_sign_in.status
     *
     * @mbggenerated Mon Apr 08 10:18:34 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column essay_sign_in.status
     *
     * @param status the value for essay_sign_in.status
     *
     * @mbggenerated Mon Apr 08 10:18:34 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column essay_sign_in.is_display
     *
     * @return the value of essay_sign_in.is_display
     *
     * @mbggenerated Mon Apr 08 10:18:34 CST 2019
     */
    public Integer getIsDisplay() {
        return isDisplay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column essay_sign_in.is_display
     *
     * @param isDisplay the value for essay_sign_in.is_display
     *
     * @mbggenerated Mon Apr 08 10:18:34 CST 2019
     */
    public void setIsDisplay(Integer isDisplay) {
        this.isDisplay = isDisplay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column essay_sign_in.gmt_create
     *
     * @return the value of essay_sign_in.gmt_create
     *
     * @mbggenerated Mon Apr 08 10:18:34 CST 2019
     */
    public Timestamp getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column essay_sign_in.gmt_create
     *
     * @param gmtCreate the value for essay_sign_in.gmt_create
     *
     * @mbggenerated Mon Apr 08 10:18:34 CST 2019
     */
    public void setGmtCreate(Timestamp gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column essay_sign_in.gmt_modified
     *
     * @return the value of essay_sign_in.gmt_modified
     *
     * @mbggenerated Mon Apr 08 10:18:34 CST 2019
     */
    public Timestamp getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column essay_sign_in.gmt_modified
     *
     * @param gmtModified the value for essay_sign_in.gmt_modified
     *
     * @mbggenerated Mon Apr 08 10:18:34 CST 2019
     */
    public void setGmtModified(Timestamp gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table essay_sign_in
     *
     * @mbggenerated Mon Apr 08 10:18:34 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", essayId=").append(essayId);
        sb.append(", essayName=").append(essayName);
        sb.append(", name=").append(name);
        sb.append(", puid=").append(puid);
        sb.append(", sex=").append(sex);
        sb.append(", unit=").append(unit);
        sb.append(", identity=").append(identity);
        sb.append(", phone=").append(phone);
        sb.append(", mail=").append(mail);
        sb.append(", note=").append(note);
        sb.append(", status=").append(status);
        sb.append(", isDisplay=").append(isDisplay);
        sb.append(", gmtCreate=").append(gmtCreate);
        sb.append(", gmtModified=").append(gmtModified);
        sb.append("]");
        return sb.toString();
    }
}