package com.example.demo.essay.model.po;

import java.sql.Timestamp;

public class EssayAwardPo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column essay_award.id
     *
     * @mbggenerated Wed Apr 03 15:18:36 CST 2019
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column essay_award.essay_id
     *
     * @mbggenerated Wed Apr 03 15:18:36 CST 2019
     */
    private String essayId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column essay_award.essay_name
     *
     * @mbggenerated Wed Apr 03 15:18:36 CST 2019
     */
    private String essayName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column essay_award.article_title
     *
     * @mbggenerated Wed Apr 03 15:18:36 CST 2019
     */
    private String articleTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column essay_award.award_name
     *
     * @mbggenerated Wed Apr 03 15:18:36 CST 2019
     */
    private String awardName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column essay_award.competitor_name
     *
     * @mbggenerated Wed Apr 03 15:18:36 CST 2019
     */
    private String competitorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column essay_award.admin_id
     *
     * @mbggenerated Wed Apr 03 15:18:36 CST 2019
     */
    private Integer adminId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column essay_award.status
     *
     * @mbggenerated Wed Apr 03 15:18:36 CST 2019
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column essay_award.is_display
     *
     * @mbggenerated Wed Apr 03 15:18:36 CST 2019
     */
    private Integer isDisplay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column essay_award.gmt_create
     *
     * @mbggenerated Wed Apr 03 15:18:36 CST 2019
     */
    private Timestamp gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column essay_award.gmt_modified
     *
     * @mbggenerated Wed Apr 03 15:18:36 CST 2019
     */
    private Timestamp gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column essay_award.id
     *
     * @return the value of essay_award.id
     *
     * @mbggenerated Wed Apr 03 15:18:36 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column essay_award.id
     *
     * @param id the value for essay_award.id
     *
     * @mbggenerated Wed Apr 03 15:18:36 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column essay_award.essay_id
     *
     * @return the value of essay_award.essay_id
     *
     * @mbggenerated Wed Apr 03 15:18:36 CST 2019
     */
    public String getEssayId() {
        return essayId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column essay_award.essay_id
     *
     * @param essayId the value for essay_award.essay_id
     *
     * @mbggenerated Wed Apr 03 15:18:36 CST 2019
     */
    public void setEssayId(String essayId) {
        this.essayId = essayId == null ? null : essayId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column essay_award.essay_name
     *
     * @return the value of essay_award.essay_name
     *
     * @mbggenerated Wed Apr 03 15:18:36 CST 2019
     */
    public String getEssayName() {
        return essayName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column essay_award.essay_name
     *
     * @param essayName the value for essay_award.essay_name
     *
     * @mbggenerated Wed Apr 03 15:18:36 CST 2019
     */
    public void setEssayName(String essayName) {
        this.essayName = essayName == null ? null : essayName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column essay_award.article_title
     *
     * @return the value of essay_award.article_title
     *
     * @mbggenerated Wed Apr 03 15:18:36 CST 2019
     */
    public String getArticleTitle() {
        return articleTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column essay_award.article_title
     *
     * @param articleTitle the value for essay_award.article_title
     *
     * @mbggenerated Wed Apr 03 15:18:36 CST 2019
     */
    public void setArticleTitle(String articleTitle) {
        this.articleTitle = articleTitle == null ? null : articleTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column essay_award.award_name
     *
     * @return the value of essay_award.award_name
     *
     * @mbggenerated Wed Apr 03 15:18:36 CST 2019
     */
    public String getAwardName() {
        return awardName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column essay_award.award_name
     *
     * @param awardName the value for essay_award.award_name
     *
     * @mbggenerated Wed Apr 03 15:18:36 CST 2019
     */
    public void setAwardName(String awardName) {
        this.awardName = awardName == null ? null : awardName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column essay_award.competitor_name
     *
     * @return the value of essay_award.competitor_name
     *
     * @mbggenerated Wed Apr 03 15:18:36 CST 2019
     */
    public String getCompetitorName() {
        return competitorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column essay_award.competitor_name
     *
     * @param competitorName the value for essay_award.competitor_name
     *
     * @mbggenerated Wed Apr 03 15:18:36 CST 2019
     */
    public void setCompetitorName(String competitorName) {
        this.competitorName = competitorName == null ? null : competitorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column essay_award.admin_id
     *
     * @return the value of essay_award.admin_id
     *
     * @mbggenerated Wed Apr 03 15:18:36 CST 2019
     */
    public Integer getAdminId() {
        return adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column essay_award.admin_id
     *
     * @param adminId the value for essay_award.admin_id
     *
     * @mbggenerated Wed Apr 03 15:18:36 CST 2019
     */
    public void setAdminId(Integer adminId) {
        this.adminId = adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column essay_award.status
     *
     * @return the value of essay_award.status
     *
     * @mbggenerated Wed Apr 03 15:18:36 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column essay_award.status
     *
     * @param status the value for essay_award.status
     *
     * @mbggenerated Wed Apr 03 15:18:36 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column essay_award.is_display
     *
     * @return the value of essay_award.is_display
     *
     * @mbggenerated Wed Apr 03 15:18:36 CST 2019
     */
    public Integer getIsDisplay() {
        return isDisplay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column essay_award.is_display
     *
     * @param isDisplay the value for essay_award.is_display
     *
     * @mbggenerated Wed Apr 03 15:18:36 CST 2019
     */
    public void setIsDisplay(Integer isDisplay) {
        this.isDisplay = isDisplay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column essay_award.gmt_create
     *
     * @return the value of essay_award.gmt_create
     *
     * @mbggenerated Wed Apr 03 15:18:36 CST 2019
     */
    public Timestamp getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column essay_award.gmt_create
     *
     * @param gmtCreate the value for essay_award.gmt_create
     *
     * @mbggenerated Wed Apr 03 15:18:36 CST 2019
     */
    public void setGmtCreate(Timestamp gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column essay_award.gmt_modified
     *
     * @return the value of essay_award.gmt_modified
     *
     * @mbggenerated Wed Apr 03 15:18:36 CST 2019
     */
    public Timestamp getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column essay_award.gmt_modified
     *
     * @param gmtModified the value for essay_award.gmt_modified
     *
     * @mbggenerated Wed Apr 03 15:18:36 CST 2019
     */
    public void setGmtModified(Timestamp gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table essay_award
     *
     * @mbggenerated Wed Apr 03 15:18:36 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", essayId=").append(essayId);
        sb.append(", essayName=").append(essayName);
        sb.append(", articleTitle=").append(articleTitle);
        sb.append(", awardName=").append(awardName);
        sb.append(", competitorName=").append(competitorName);
        sb.append(", adminId=").append(adminId);
        sb.append(", status=").append(status);
        sb.append(", isDisplay=").append(isDisplay);
        sb.append(", gmtCreate=").append(gmtCreate);
        sb.append(", gmtModified=").append(gmtModified);
        sb.append("]");
        return sb.toString();
    }
}