package com.example.demo.essay.model.po;

import java.sql.Timestamp;
import java.util.Date;

public class EssayInfoPo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column essay_info.id
     *
     * @mbggenerated Mon Jul 15 19:56:38 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column essay_info.title
     *
     * @mbggenerated Mon Jul 15 19:56:38 CST 2019
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column essay_info.theme
     *
     * @mbggenerated Mon Jul 15 19:56:38 CST 2019
     */
    private String theme;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column essay_info.claim
     *
     * @mbggenerated Mon Jul 15 19:56:38 CST 2019
     */
    private String claim;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column essay_info.sponsor
     *
     * @mbggenerated Mon Jul 15 19:56:38 CST 2019
     */
    private String sponsor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column essay_info.screenshot
     *
     * @mbggenerated Mon Jul 15 19:56:38 CST 2019
     */
    private String screenshot;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column essay_info.start
     *
     * @mbggenerated Mon Jul 15 19:56:38 CST 2019
     */
    private Timestamp start;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column essay_info.duration
     *
     * @mbggenerated Mon Jul 15 19:56:38 CST 2019
     */
    private Timestamp duration;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column essay_info.uuid
     *
     * @mbggenerated Mon Jul 15 19:56:38 CST 2019
     */
    private String uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column essay_info.admin_id
     *
     * @mbggenerated Mon Jul 15 19:56:38 CST 2019
     */
    private Integer adminId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column essay_info.admin_unit_id
     *
     * @mbggenerated Mon Jul 15 19:56:38 CST 2019
     */
    private Integer adminUnitId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column essay_info.admin_name
     *
     * @mbggenerated Mon Jul 15 19:56:38 CST 2019
     */
    private String adminName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column essay_info.approval_type
     *
     * @mbggenerated Mon Jul 15 19:56:38 CST 2019
     */
    private Integer approvalType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column essay_info.status
     *
     * @mbggenerated Mon Jul 15 19:56:38 CST 2019
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column essay_info.is_display
     *
     * @mbggenerated Mon Jul 15 19:56:38 CST 2019
     */
    private Boolean isDisplay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column essay_info.gmt_create
     *
     * @mbggenerated Mon Jul 15 19:56:38 CST 2019
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column essay_info.gmt_modified
     *
     * @mbggenerated Mon Jul 15 19:56:38 CST 2019
     */
    private Date gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column essay_info.id
     *
     * @return the value of essay_info.id
     *
     * @mbggenerated Mon Jul 15 19:56:38 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column essay_info.id
     *
     * @param id the value for essay_info.id
     *
     * @mbggenerated Mon Jul 15 19:56:38 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column essay_info.title
     *
     * @return the value of essay_info.title
     *
     * @mbggenerated Mon Jul 15 19:56:38 CST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column essay_info.title
     *
     * @param title the value for essay_info.title
     *
     * @mbggenerated Mon Jul 15 19:56:38 CST 2019
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column essay_info.theme
     *
     * @return the value of essay_info.theme
     *
     * @mbggenerated Mon Jul 15 19:56:38 CST 2019
     */
    public String getTheme() {
        return theme;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column essay_info.theme
     *
     * @param theme the value for essay_info.theme
     *
     * @mbggenerated Mon Jul 15 19:56:38 CST 2019
     */
    public void setTheme(String theme) {
        this.theme = theme == null ? null : theme.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column essay_info.claim
     *
     * @return the value of essay_info.claim
     *
     * @mbggenerated Mon Jul 15 19:56:38 CST 2019
     */
    public String getClaim() {
        return claim;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column essay_info.claim
     *
     * @param claim the value for essay_info.claim
     *
     * @mbggenerated Mon Jul 15 19:56:38 CST 2019
     */
    public void setClaim(String claim) {
        this.claim = claim == null ? null : claim.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column essay_info.sponsor
     *
     * @return the value of essay_info.sponsor
     *
     * @mbggenerated Mon Jul 15 19:56:38 CST 2019
     */
    public String getSponsor() {
        return sponsor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column essay_info.sponsor
     *
     * @param sponsor the value for essay_info.sponsor
     *
     * @mbggenerated Mon Jul 15 19:56:38 CST 2019
     */
    public void setSponsor(String sponsor) {
        this.sponsor = sponsor == null ? null : sponsor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column essay_info.screenshot
     *
     * @return the value of essay_info.screenshot
     *
     * @mbggenerated Mon Jul 15 19:56:38 CST 2019
     */
    public String getScreenshot() {
        return screenshot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column essay_info.screenshot
     *
     * @param screenshot the value for essay_info.screenshot
     *
     * @mbggenerated Mon Jul 15 19:56:38 CST 2019
     */
    public void setScreenshot(String screenshot) {
        this.screenshot = screenshot == null ? null : screenshot.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column essay_info.start
     *
     * @return the value of essay_info.start
     *
     * @mbggenerated Mon Jul 15 19:56:38 CST 2019
     */
    public Timestamp getStart() {
        return start;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column essay_info.start
     *
     * @param start the value for essay_info.start
     *
     * @mbggenerated Mon Jul 15 19:56:38 CST 2019
     */
    public void setStart(Timestamp start) {
        this.start = start;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column essay_info.duration
     *
     * @return the value of essay_info.duration
     *
     * @mbggenerated Mon Jul 15 19:56:38 CST 2019
     */
    public Timestamp getDuration() {
        return duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column essay_info.duration
     *
     * @param duration the value for essay_info.duration
     *
     * @mbggenerated Mon Jul 15 19:56:38 CST 2019
     */
    public void setDuration(Timestamp duration) {
        this.duration = duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column essay_info.uuid
     *
     * @return the value of essay_info.uuid
     *
     * @mbggenerated Mon Jul 15 19:56:38 CST 2019
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column essay_info.uuid
     *
     * @param uuid the value for essay_info.uuid
     *
     * @mbggenerated Mon Jul 15 19:56:38 CST 2019
     */
    public void setUuid(String uuid) {
        this.uuid = uuid == null ? null : uuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column essay_info.admin_id
     *
     * @return the value of essay_info.admin_id
     *
     * @mbggenerated Mon Jul 15 19:56:38 CST 2019
     */
    public Integer getAdminId() {
        return adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column essay_info.admin_id
     *
     * @param adminId the value for essay_info.admin_id
     *
     * @mbggenerated Mon Jul 15 19:56:38 CST 2019
     */
    public void setAdminId(Integer adminId) {
        this.adminId = adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column essay_info.admin_unit_id
     *
     * @return the value of essay_info.admin_unit_id
     *
     * @mbggenerated Mon Jul 15 19:56:38 CST 2019
     */
    public Integer getAdminUnitId() {
        return adminUnitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column essay_info.admin_unit_id
     *
     * @param adminUnitId the value for essay_info.admin_unit_id
     *
     * @mbggenerated Mon Jul 15 19:56:38 CST 2019
     */
    public void setAdminUnitId(Integer adminUnitId) {
        this.adminUnitId = adminUnitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column essay_info.admin_name
     *
     * @return the value of essay_info.admin_name
     *
     * @mbggenerated Mon Jul 15 19:56:38 CST 2019
     */
    public String getAdminName() {
        return adminName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column essay_info.admin_name
     *
     * @param adminName the value for essay_info.admin_name
     *
     * @mbggenerated Mon Jul 15 19:56:38 CST 2019
     */
    public void setAdminName(String adminName) {
        this.adminName = adminName == null ? null : adminName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column essay_info.approval_type
     *
     * @return the value of essay_info.approval_type
     *
     * @mbggenerated Mon Jul 15 19:56:38 CST 2019
     */
    public Integer getApprovalType() {
        return approvalType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column essay_info.approval_type
     *
     * @param approvalType the value for essay_info.approval_type
     *
     * @mbggenerated Mon Jul 15 19:56:38 CST 2019
     */
    public void setApprovalType(Integer approvalType) {
        this.approvalType = approvalType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column essay_info.status
     *
     * @return the value of essay_info.status
     *
     * @mbggenerated Mon Jul 15 19:56:38 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column essay_info.status
     *
     * @param status the value for essay_info.status
     *
     * @mbggenerated Mon Jul 15 19:56:38 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column essay_info.is_display
     *
     * @return the value of essay_info.is_display
     *
     * @mbggenerated Mon Jul 15 19:56:38 CST 2019
     */
    public Boolean getIsDisplay() {
        return isDisplay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column essay_info.is_display
     *
     * @param isDisplay the value for essay_info.is_display
     *
     * @mbggenerated Mon Jul 15 19:56:38 CST 2019
     */
    public void setIsDisplay(Boolean isDisplay) {
        this.isDisplay = isDisplay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column essay_info.gmt_create
     *
     * @return the value of essay_info.gmt_create
     *
     * @mbggenerated Mon Jul 15 19:56:38 CST 2019
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column essay_info.gmt_create
     *
     * @param gmtCreate the value for essay_info.gmt_create
     *
     * @mbggenerated Mon Jul 15 19:56:38 CST 2019
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column essay_info.gmt_modified
     *
     * @return the value of essay_info.gmt_modified
     *
     * @mbggenerated Mon Jul 15 19:56:38 CST 2019
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column essay_info.gmt_modified
     *
     * @param gmtModified the value for essay_info.gmt_modified
     *
     * @mbggenerated Mon Jul 15 19:56:38 CST 2019
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table essay_info
     *
     * @mbggenerated Mon Jul 15 19:56:38 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", title=").append(title);
        sb.append(", theme=").append(theme);
        sb.append(", claim=").append(claim);
        sb.append(", sponsor=").append(sponsor);
        sb.append(", screenshot=").append(screenshot);
        sb.append(", start=").append(start);
        sb.append(", duration=").append(duration);
        sb.append(", uuid=").append(uuid);
        sb.append(", adminId=").append(adminId);
        sb.append(", adminUnitId=").append(adminUnitId);
        sb.append(", adminName=").append(adminName);
        sb.append(", approvalType=").append(approvalType);
        sb.append(", status=").append(status);
        sb.append(", isDisplay=").append(isDisplay);
        sb.append(", gmtCreate=").append(gmtCreate);
        sb.append(", gmtModified=").append(gmtModified);
        sb.append("]");
        return sb.toString();
    }
}